name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Go
      uses: actions/setup-go@v5.4.0
      with:
        go-version: 1.20

    - name: Build
      run: |
        go build -o vidfusion${{ matrix.os == 'windows-latest' && '.exe' || '' }} vidfusion.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: vidfusion-${{ matrix.os }}
        path: vidfusion${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: |
          vidfusion_ubuntu-latest
          vidfusion_windows-latest.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}