name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Go
      uses: actions/setup-go@v5.4.0
      with:
        go-version: 1.20

    - name: Build
      run: |
        go build -o vidfusion${{ matrix.os == 'windows-latest' && '.exe' || '' }} vidfusion.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: vidfusion-${{ matrix.os }}
        path: vidfusion${{ matrix.os == 'windows-latest' && '.exe' || '' }}
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Download Ubuntu artifact
      uses: actions/download-artifact@v4.2.1
      with:
        name: vidfusion-ubuntu-latest
        path: ./'

    - name: Download Windows artifact
      uses: actions/download-artifact@v4.2.1
      with:
        name: vidfusion-windows-latest
        path: ./'

    - name: Rename artifacts for release
      run: |
        mv vidfusion vidfusion-linux
        mv vidfusion.exe vidfusion-windows.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: |
          vidfusion-linux
          vidfusion-windows.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}