name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o vidfusion_windows.exe vidfusion.go

    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -o vidfusion_linux vidfusion.go

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: vidfusion-windows
        path: vidfusion_windows.exe

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: vidfusion-linux
        path: vidfusion_linux

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          vidfusion_windows.exe
          vidfusion_linux
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}